# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish plugin to the Gradle Plugin Portal

run-name: Publish to the Gradle Plugin Portal and switch over to ${{ inputs.developmentVersion }}

on:
  workflow_dispatch:
    inputs:
      developmentVersion:
        description: "Next development version"
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Print the next development version
        run: echo "${{ inputs.developmentVersion }}"

      - name: Configure Git user
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean release -Prelease.newVersion=${{ inputs.developmentVersion }}