name: Basic test

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure Git user
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Test push privs
        run: |
          touch testfile
          git add -A
          git commit -m "testfile added"

      - name: Get commit sha
        run: |
          echo "NEW_COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/heads/main",
              sha: "${{ env.NEW_COMMIT_SHA }}"
            })